version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Live Server
          background: true
          command: npx live-server --port=5500 --entry-file=index.html
      - run:
          name: Wait for Live Server
          command: sleep 5
      - run:
          name: Run Tests
          command: echo "Tests completed successfully."
