version: 2.1
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install Live Server
          command: npm install -g live-server
      - run:
          name: Start Live Server
          command: live-server --port=5500 --entry-file=index.html
